version: '2'
services:
  web:
    # Nginx WebServer. links to PHP Container.
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    links:
      - php
    restart: always
    volumes:
      # App Code. Same as PHP Container
      - ../:/code
      # Nginx main Conf.
      - ./server.conf:/etc/nginx/conf.d/default.conf
      # Persistent Log of Nginx Server
      - ./LOG/nginx:/var/log/nginx
      # Certs
      - ./sendy.key:/etc/nginx/sendy.key
      - ./sendy.pem:/etc/nginx/sendy.pem
  php:
    # PHP Container. links to Database Containers.
    build:
      context: ./Dockerfiles
      dockerfile: docker.sample
    # Change image directive based on your needs
    image: php-fpm:version
    links:
      # connection to databases. Postgresql and Mysql are available. anything else should work
      - psql
      - mysql
    volumes:
      # App Code. Same as Nginx Container
      - ../:/code
      # PHP config file
      - ./php.ini:/usr/local/etc/php/conf.d/01-custom.ini
      # Persistent Log of PHP-FPM
      - ./LOG/nginx:/var/log/nginx
  mysql:
    # MySql Container.
    image: mysql:latest
    volumes:
      # Persistent Data Volume
      - ./DB/mysql/rayvista:/var/lib/mysql
      # Custom CNF file. remove if you don't have any cutomization
      - ./mysql.cnf:/etc/mysql/conf.d/01-custom.cnf
    environment:
      # Auth Information
      - MYSQL_DATABASE=sendy
      - MYSQL_USER=sendy
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
